// Palette = single source of truth for PawTown colors.
using System.Collections.Generic;

namespace PawTown
{
    public static class PawTownPalette
    {
        public static readonly Dictionary<string, string> Base = new Dictionary<string, string>
        {
            { "Grass", "#8CC84B" },
            { "GrassDark", "#72B23F" },
            { "Sidewalk", "#ECE1C8" },
            { "Asphalt", "#454955" },
            { "LineWhite", "#F7F6F0" },
            { "LineYellow", "#F4C430" },
            { "Water", "#5CBDE8" },
            { "WaterEdge", "#9FDDF5" },
            { "Sand", "#E9D49A" },
            { "Dirt", "#B98A5E" },
            { "Gravel", "#A8A097" },
            { "Sleeper", "#7A5236" },
            { "RailMetal", "#A3A9B3" },
            { "Stone", "#CFC6B8" },
            { "StoneDark", "#A1978A" },
            { "Wood", "#B97E4C" },
            { "WoodDark", "#80542F" },
            { "Trunk", "#8A5A3B" },
            { "Rubber", "#5A5E68" },
            { "Leaf1", "#5DB343" },
            { "Leaf2", "#86CC4E" },
            { "Leaf3", "#3F9A45" },
            { "LeafOrange", "#EE9A3A" },
            { "LeafPink", "#E384B9" },
            { "LeafYellow", "#F2C94C" },
            { "Pine", "#3A9A5E" },
            { "Bush", "#55AC40" },
            { "RoofRed", "#DE5A3F" },
            { "RoofBlue", "#4B83C9" },
            { "RoofOrange", "#E9853D" },
            { "RoofTeal", "#3FA39A" },
            { "RoofBrown", "#9A5B3A" },
            { "WallCream", "#F6E7C8" },
            { "WallPeach", "#F4BE90" },
            { "WallYellow", "#F7D88F" },
            { "WallBlue", "#B9D9EC" },
            { "WallPink", "#F6CBD3" },
            { "WallBrick", "#CF7A55" },
            { "Window", "#A6DDF5" },
            { "Frame", "#FFFFFF" },
            { "Door", "#8E5A3A" },
            { "Awning1", "#E2504A" },
            { "AwningBlue", "#4B83C9" },
            { "AwningGreen", "#4DAF6A" },
            { "Metal", "#4C515D" },
            { "MetalLight", "#BCC1CA" },
            { "Black", "#2E2F38" },
            { "Red", "#E8433A" },
            { "White", "#FAFAF7" },
            { "Yellow", "#F7C531" },
            { "Mountain", "#C29469" },
            { "MountainDark", "#A07750" },
            { "Snow", "#FFFFFF" },
            { "Hill", "#9ACD5E" },
            { "HillDark", "#7DB54C" },
            { "Field", "#E2C55E" },
            { "FieldGreen", "#A8CF5F" },
            { "Pink", "#F29BB8" },
            { "Flower1", "#FF7A8A" },
            { "Flower2", "#FFD65C" },
            { "Flower3", "#B98BFF" },
            { "Cloud", "#FFFFFF" },
            { "CatOrange", "#F59A45" },
            { "CatStripe", "#DB7429" },
            { "CatCream", "#FFF3E2" },
            { "CatPink", "#F7A1B3" },
            { "EyeBlack", "#2A2230" },
            { "Skin1", "#F8D5B5" },
            { "Skin2", "#E3AB82" },
            { "Skin3", "#A9714E" },
            { "HairBrown", "#6E4631" },
            { "HairBlack", "#2F2723" },
            { "HairBlond", "#F2C76E" },
            { "HairGrey", "#DADADA" },
            { "HairRed", "#C9573A" },
            { "Jeans", "#4E73AD" },
            { "Shoe", "#5B3B2D" },
            { "Purple", "#9D7BD9" },
            { "FishGold", "#EBA24C" },
            { "FishLight", "#F6C877" },
            { "FishDark", "#C47A2E" },
            { "YarnPink", "#E58AB4" },
            { "YarnDark", "#C0638E" },
            { "Outline", "#2B2320" },
        };

        /// <summary>Self-lit lamp colors (traffic lights, street lamps).</summary>
        public static readonly Dictionary<string, string> Emissive = new Dictionary<string, string>
        {
            { "LampRed", "#FF3B30" },
            { "LampYellow", "#FFC400" },
            { "LampGreen", "#35E06A" },
            { "LampWarm", "#FFE7A0" },
            { "PedRed", "#FF3B30" },
            { "PedGreen", "#35E06A" },
            { "CrossRed", "#FF3B30" },
        };
    }
}
